### PR TITLE
Rename template.md to 20180803-tanj-mcmeans-m1.md

### PR DESCRIPTION
**Pull request by TMcMeans**

### CODE REVIEW

**Comment by TMcMeans** [comment]
Changed file name

**Comment by LouisaBarrett** [comment]
Have you updated the contents of this file? Looks like this is just for the file name change.

**Comment by TMcMeans** [comment]
I added the portfolio with on another pull request from yesterday? Is it all missing?? OH NO :((((

**Comment by LouisaBarrett** [comment]
Ok, cool! The first commit is merged in now, I'll close this one 💯

**Pull request closed without merging**
