### PR TITLE
Fred Block

### PR DESCRIPTION
**Pull request by blocknroll**
new file:   20150814-fred_block-m4.markdown

### CODE REVIEW

**Comment by loriculberson** [comment]
You've made some good progress this module understanding JavaScript. Keep up the studying. I think you should pair with mentors multiple times each week. It's important to work with someone who can teach you while you are honing your skills.

**Comment by tessgriffin** [comment]
Hey Fred! It's been really great having you with 1502 these last two modules. I wish I would've had the chance to work with you more. I agree with Lori about pairing with mentors. You can gain a lot even when you're not working on assignments.

**Comment by blocknroll** [comment]
Ready to merge.

**Comment by patrickmedaugh** [comment]
First of all, you helped me figure out how the commenting thing works! Most of all you've just been a great guy who even since module 1 when we were in the same posse were very welcoming and always had a positive attitude. I think you've come a long way and now are creating all sorts of IoT apps with drones and really advanced stuff. It's great to see.

**Comment by Carmer** [comment]
Fred, man, a better compliment has never been given. Thank you. Hi-Five! We've talked about it before, but I'm excited to see where this all leads us. One thing I really admire about it is your tenacity in the pursuit towards the things you like. That and your positive nature make for an awesome human. Really glad to have met you, and now I'm glad that I get to know you. Block on.

**Comment by haveanicedavid** [comment]
Entering into final projects, I gave serious consideration to joining you just so we could work together again. You have an admirable quality of optimism that is contagious, in addition to a serious work ethic and artistic eye. I'm also pretty sure your life story could be featured in a Dos Equis commercial.

**Comment by mihir787** [comment]
Fred, you have an awesome addition to our module.  You are a man who learned to code because you were truly interested in it. Thank you for the lesson on the Raspberry Pi.

**Pull request merged**
