### PR TITLE
WIP eric's portfolio

### PR DESCRIPTION
**Pull request by eric-dowty**

### CODE REVIEW

**Comment by patrickmedaugh** [comment]
Eric you simply won't be outworked. It was great getting to work with you on the Pivot and at the QuickLeft hackathon. You're great in teams because you always have a good input and are constantly looking at what we can implement next, how we can do it and how to bring things all together. It's been a privilege. Best of luck to you.

**Comment by boomkenster** [comment]
Eric is a great person to have around. His problem solving skills and work ethic is unmatched. It was great seeing him start to open up to us and get to know him a bit better. He'll be amazing!

**Comment by tleskin** [comment]
Eric, you really are unmatched when it comes to problem solving and work ethic and you're an extremely dedicated developer. I think out of just about everyone in 1502, you're someone one who I've seen some of biggest changes from. As time went on, you opened up to us and me personally, and we got to talking about issues you've encountered such as while working on certain teams, issues in the industry, etc. One thing I remember from Module 1 is that we were pairing on a challenge and we were cruising along, but I was pretty lost. As the modules went on, you learned to make sure everyone was on the same page and understands everything and I think that's a really great ability to have. When we got to Module 3 and the Pivot, it seemed we were an unstoppable pair with our abilities mashing perfectly, your ability to quickly drive code and figure things out, then mine to spot errors and step back and quickly come up with a solution so we could keep going. Going into the workplace, you're going to be an awesome team member!

**Comment by kylehenson** [comment]
Eric: Your intelligence and drive are forces to be reckoned with! There is not problem you can't solve, no matter how crazy the solution might be. In addition, you are one of the easiest people to work with. You are a leader, and anyone that works on your team will see that immediately!

**Pull request merged**
