### PR TITLE
First draft. Pending personal review and unfinished community contrib…

### PR DESCRIPTION
**Pull request by davemaurer**
…utions

Also, one line in the submission_guidelines was hard to read so I wrapped it.

### CODE REVIEW

**Comment by stevekinney** [comment]
I love the level of detail in your portfolio submission.

**Comment by worace** [comment]
:+1:

**Comment by mikedao** [comment]
I wholly concur - this is great.

**Comment by davemaurer** [comment]
Changed the wrap in the sample file back to the way it was. Added several more commits.

**Pull request merged**
