### PR TITLE
Andrew carmer

### PR DESCRIPTION
**Pull request by Carmer**
Pull Request

### CODE REVIEW

**Comment by blocknroll** [comment]
I'd like to start by saying that I don't think your high-fives are at all uncomfortably long or awkward.  In fact, I've always remarked on the precision, power and passion you bring to your high-fiving pursuits.  Your portfolio also shows the same commitment to excellence.  It's been absolutely great to work with you throughout the last two modules, on projects big and small. Our pivot project was a fun and interesting challenge and I'm happy I had a chance to work so closely with you.  You clearly have put in a great effort at Turing and the results show.  Quite simply, you're a great guy to be around and to work with. High-Five!!!

**Comment by loriculberson** [comment]
Mr. Positive Problem Solver! You're good at breaking down concepts into small pieces. That means you will be a good teacher.

**Comment by tleskin** [comment]
I've always felt that you were one of the easiest people to work with. I remember you also saying that you felt sometimes you would be demanding and take over, but I've never seen that. For however long you stay working at Turing, I feel that they'll be lucky to have you since you're one of the most approachable, caring and hard-working people I know. As long as you keep working hard and collaborating with the community whether Turing or the larger development community, I think your career is going to be awesome.

**Comment by patrickmedaugh** [comment]
You were the first person I paired with and I realized I had a lot to learn about working with other people and thinking out loud and being able to go with the flow and follow someone else's lead while coding. Any time I'm pairing I go back to that. You're a good guy and always willing to help any and everyone.

**Pull request merged**
