### PR TITLE
Kenny Chen

### PR DESCRIPTION
**Pull request by boomkenster**

### CODE REVIEW

**Comment by tleskin** [comment]
KENSTER! You've always been a great partner to work with and I'm glad that we had the chance to work on the final project together. We might not have been completely successful with Ember, but we did learn a lot and gain familiarity with it. I think one of your strengths that will be an asset in the workplace is your need to help others and make sure they are on the same page as you. I think we've all come a long way since Module 1 and I still remember pairing with you on the encryptor when we had no idea how to do it. You say that you can't focus as hard and as long as others can, but I don't believe that, since during the final assessment, you were there working until the early morning hours just as long as anybody else. You're an extremely loyal and dedicated individual, which is something I'll always respect about you.

**Comment by Carmer** [comment]
There are people that are great. There are "stand up guys". There are great programmers. There are men that everyone can learn from, and ones that many people admire and respect. Then, there's guys like you who seem to be all of the above. You will be missed around here by more people than just me. And I'm going to miss you a lot. There are a lot of things I admire, but in regards to being at Turing, I admire you most for your attitude about everything and you're ability to keep everything in perspective. I'm already looking forward to coming to visit you in NY.

**Comment by haveanicedavid** [comment]
I'm going to reiterate what Andrew said. Any time I approached a situation with negativity, you managed to not only lift my spirits, but humble me in your persistent optimism and endearing effort to make the best of a difficult situation. I wouldn't be surprised if Turing becomes a 'feed-engine' to Digital Ocean after they see how far you've come in the last 7 months

**Comment by mihir787** [comment]
The Kennster of the Boom, from our early days in module 1 to now, we have grown a lot together as friends and developers.  You have a calming effect on people that brings out the best in them.  Thanks for the jokes, laughs, and the damn good code.  Go back to NYC and show digital ocean your made skillz.  You gonna make us proud.

**Pull request merged**
