### PR TITLE
Submit Portfolio Helen Dechat FEM4

### PR DESCRIPTION
**Pull request by hdechat**

### CODE REVIEW

**Comment by robbiejaeger** [comment]
@hdechat Can you modify your link so that it will show your calendar events for anyone who views the link? If I go to the link, it just shows my own calendar. After that, you're good to merge.

**Comment by hdechat** [comment]
Oops!

**Comment by hdechat** [comment]
Okay, should be fixed

**Comment by robbiejaeger** [comment]
@hdechat I still only see my own calendar with [this link](https://calendar.google.com/calendar/r/week/2018/8/6) in your markdown. Try having someone else open it to see what they see.

**Comment by hdechat** [comment]
Sorry about that Robbie! It should be good now

**Pull request merged**
