### PR TITLE
Patrick Medaugh

### PR DESCRIPTION
**Pull request by patrickmedaugh**

### CODE REVIEW

**Comment by blocknroll** [comment]
It's been really great to work with you and to get to know you, Patrick!  I was bummed that we didn't get to officially hang out anymore after our posse was disbanded – but it's been great to spend more time with you after I joined 1502. You always bring a great energy to our group and I'm always looking forward to talking with you about the latest JavaScript goodies!

**Comment by tleskin** [comment]
I agree with Fred that you bring a great energy as well especially when it comes to anything related to JavaScript, meetups (for Go/JavaScript) or companies you're interested in like Pivotal. You were always up on trying to learn the next big thing like Go or the MEAN Stack/Mongo. I'd say just keep up that energy and interest and you're going to have an awesome career.

**Comment by haveanicedavid** [comment]
I always really enjoyed working with Pat. He has a wide knowledge base, and an element of creativity that always results in some interesting ideas and new ways of approaching problems. Also consistently made an effort to get folks involved in local networking events

**Comment by kylehenson** [comment]
Patrick: You always have a deep interest in what you are currently working on and have an eye toward what you will be learning next. You are always reaching for the stars when it comes to writing exceptional code, learning new languages, and frameworks, and all around having fun!

**Comment by loriculberson** [comment]
You have a great way of explaining complex topics. I remember how you explained the Superhero "good" and "evil" scale. That really helped our group implement feature in our project.

**Comment by mihir787** [comment]
You are one solid human being.  You are someone who I feel that is going to do great in the workpalce.  You have a genuine interest and a calm demeanor which make you an amazing pairing partner.  Go out and make the world yours.

**Pull request merged**
